enum Screenshots {
  DRAFTED_LANDING = "DRAFTED_LANDING",
  DRAFTED_PROJECTS = "DRAFTED_PROJECTS",
  DRAFTED_ABOUT = "DRAFTED_ABOUT",
  DRAFTED_PROJECT_OPEN = "DRAFTED_PROJECT_OPEN",
}

export default Screenshots;
