enum Technologies {
  MONGO_DB = "MONGO_DB",
  NODE_JS = "NODE_JS",
  EXPRESS_JS = "EXPRESS_JS",
  REACT_JS = "REACT_JS",
  POSTGRESQL = "POSTGRESQL",
  AXIOS = "AXIOS",
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  NEXT_JS = "NEXT_JS",
}

export default Technologies;
